<?php
    dump($block->getMessage());
    dump($block->getData('view_model'));
    dump($block->getData('block'));
    /** @var Boxydev\Learn\ViewModel\ $viewModel */
    $viewModel = $block->getData('view_model');
?>

<h1><?= $viewModel->say(); ?></h1>
<h2>Contenu de la requête :</h2>
<?php dump($viewModel->getRequest()); ?>
<h2>Client : <?= __('Hello World'); ?></h2>
<?php dump($viewModel->getSession()->getCustomer()->getEmail()); ?>
