<?php
$data = $this->getRequest()->getPost();
?>

<form method="post" data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <div class="field name required">
            <label class="label" for="name">
                <span>Name</span>
            </label>
            <div class="control">
                <input name="name" id="name" title="Name" class="input-text" type="text" data-validate="{required:true}" value="<?= $data['name'] ?? null; ?>">
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email">
                <span>Email</span>
            </label>
            <div class="control">
                <input name="email" id="email" title="Email" class="input-email" type="email" data-validate="{required:true}" value="<?= $data['email'] ?? null; ?>">
            </div>
        </div>
    </fieldset>

    <button class="action submit primary">Envoyer</button>
</form>
